/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import config.Koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author najwa
 */
public class FormMenuUtama extends javax.swing.JFrame {
    Connection conn;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormMenuUtama.class.getName());

    /**
     * Creates new form FormMenuUtama
     */
    public FormMenuUtama() {
        initComponents();
        setLocationRelativeTo(null);
        conn = Koneksi.getConnection();
        tampilDashboard();
    }

    private void tampilDashboard() {
        try {
            String sqlJenis = "SELECT COUNT(*) AS total FROM jenis_barang";
            PreparedStatement pstJenis = conn.prepareStatement(sqlJenis);
            ResultSet rsJenis = pstJenis.executeQuery();
            if (rsJenis.next()) {
                lblTotalJenis.setText("Total Jenis Barang : " + rsJenis.getInt("total"));
            }

            String sqlBarang = "SELECT COUNT(*) AS total FROM barang";
            PreparedStatement pstBarang = conn.prepareStatement(sqlBarang);
            ResultSet rsBarang = pstBarang.executeQuery();
            if (rsBarang.next()) {
                lblTotalBarang.setText("Total Barang : " + rsBarang.getInt("total"));
            }

            String sqlStok = "SELECT IFNULL(SUM(jumlah), 0) AS total FROM barang";
            PreparedStatement pstStok = conn.prepareStatement(sqlStok);
            ResultSet rsStok = pstStok.executeQuery();
            if (rsStok.next()) {
                lblTotalStok.setText("Total Stok : " + rsStok.getInt("total"));
            }

            String sqlMasuk = "SELECT COUNT(*) AS total FROM barang_masuk";
            PreparedStatement pstMasuk = conn.prepareStatement(sqlMasuk);
            ResultSet rsMasuk = pstMasuk.executeQuery();
            if (rsMasuk.next()) {
                lblTotalMasuk.setText("Transaksi Masuk : " + rsMasuk.getInt("total"));
            }

            String sqlKeluar = "SELECT COUNT(*) AS total FROM barang_keluar";
            PreparedStatement pstKeluar = conn.prepareStatement(sqlKeluar);
            ResultSet rsKeluar = pstKeluar.executeQuery();
            if (rsKeluar.next()) {
                lblTotalKeluar.setText("Transaksi Keluar : " + rsKeluar.getInt("total"));
            }

         } catch (SQLException e) {
           JOptionPane.showMessageDialog(this, "Gagal menampilkan dashboard: " + e.getMessage());
         }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDataBarang = new javax.swing.JButton();
        btnBarangMasuk = new javax.swing.JButton();
        btnBarangKeluar = new javax.swing.JButton();
        btnLaporanStok = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTotalJenis = new javax.swing.JLabel();
        lblTotalBarang = new javax.swing.JLabel();
        lblTotalStok = new javax.swing.JLabel();
        lblTotalMasuk = new javax.swing.JLabel();
        lblTotalKeluar = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 236));

        btnDataBarang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDataBarang.setForeground(new java.awt.Color(0, 102, 204));
        btnDataBarang.setText("Data Barang ");
        btnDataBarang.addActionListener(this::btnDataBarangActionPerformed);

        btnBarangMasuk.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBarangMasuk.setForeground(new java.awt.Color(0, 204, 153));
        btnBarangMasuk.setText("Barang Masuk");
        btnBarangMasuk.addActionListener(this::btnBarangMasukActionPerformed);

        btnBarangKeluar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBarangKeluar.setForeground(new java.awt.Color(204, 204, 0));
        btnBarangKeluar.setText("Barang Keluar");
        btnBarangKeluar.addActionListener(this::btnBarangKeluarActionPerformed);

        btnLaporanStok.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLaporanStok.setForeground(new java.awt.Color(255, 0, 204));
        btnLaporanStok.setText("Laporan Stok");
        btnLaporanStok.setToolTipText("");
        btnLaporanStok.addActionListener(this::btnLaporanStokActionPerformed);

        btnKeluar.setForeground(new java.awt.Color(0, 51, 255));
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(this::btnKeluarActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("KMERCH INVENTORY ");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel2.setText("Aplikasi Gudang Merchandise K-Pop ");

        lblTotalJenis.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTotalJenis.setForeground(new java.awt.Color(102, 0, 255));
        lblTotalJenis.setText("Total Jenis Barang ");

        lblTotalBarang.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTotalBarang.setForeground(new java.awt.Color(153, 153, 0));
        lblTotalBarang.setText("Total Barang");

        lblTotalStok.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTotalStok.setForeground(new java.awt.Color(153, 0, 153));
        lblTotalStok.setText("Total Stok");

        lblTotalMasuk.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTotalMasuk.setForeground(new java.awt.Color(0, 204, 102));
        lblTotalMasuk.setText("Transaksi Masuk");

        lblTotalKeluar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTotalKeluar.setForeground(new java.awt.Color(255, 51, 0));
        lblTotalKeluar.setText("Transaksi Keluar");

        btnRefresh.setForeground(new java.awt.Color(0, 51, 255));
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTotalBarang)
                            .addComponent(lblTotalStok)
                            .addComponent(lblTotalMasuk)
                            .addComponent(lblTotalKeluar)
                            .addComponent(lblTotalJenis)
                            .addComponent(btnRefresh))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDataBarang)
                    .addComponent(btnLaporanStok))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBarangMasuk)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnKeluar))
                    .addComponent(btnBarangKeluar))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalJenis)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDataBarang)
                        .addComponent(btnBarangMasuk)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBarangKeluar)
                            .addComponent(btnLaporanStok))
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalBarang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTotalStok)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(lblTotalMasuk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotalKeluar)
                .addGap(18, 18, 18)
                .addComponent(btnRefresh)
                .addGap(3, 3, 3)
                .addComponent(btnKeluar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDataBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataBarangActionPerformed
        // TODO add your handling code here:
        new FormBarang().setVisible(true);
    }//GEN-LAST:event_btnDataBarangActionPerformed

    private void btnBarangMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarangMasukActionPerformed
        // TODO add your handling code here:
        new FormBarangMasuk().setVisible(true);
    }//GEN-LAST:event_btnBarangMasukActionPerformed

    private void btnBarangKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarangKeluarActionPerformed
        // TODO add your handling code here:
        new FormBarangKeluar().setVisible(true);
    }//GEN-LAST:event_btnBarangKeluarActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(
        this, "Yakin Sudah ingin keluar aplikasi?", "Konfirmasi",
        javax.swing.JOptionPane.YES_OPTION
        );
        
        if(konfirmasi == javax.swing.JOptionPane.YES_OPTION){
        System.exit(0);
      }
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnLaporanStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanStokActionPerformed
        // TODO add your handling code here:
        new FormLaporanStok().setVisible(true);
    }//GEN-LAST:event_btnLaporanStokActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        tampilDashboard();
    }//GEN-LAST:event_btnRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormMenuUtama().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBarangKeluar;
    private javax.swing.JButton btnBarangMasuk;
    private javax.swing.JButton btnDataBarang;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnLaporanStok;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblTotalBarang;
    private javax.swing.JLabel lblTotalJenis;
    private javax.swing.JLabel lblTotalKeluar;
    private javax.swing.JLabel lblTotalMasuk;
    private javax.swing.JLabel lblTotalStok;
    // End of variables declaration//GEN-END:variables
}
